import React, { useRef, useState } from 'react';
import { ContentRenderer } from '../utils/contentRenderer';
import MatchColumnsModal from './MatchColumnsModal';

function keysFor(style, count) {
  return Array.from({ length: count }, (_, index) => style === 'alpha' ? String.fromCharCode(65 + index) : String(index + 1));
}

function QuestionEditorForm({ initialQuestion = {}, categories = [], submitLabel = 'Save Question', onSubmit, onCancel, onDelete, statusMessage = '', statusError = '' }) {
  const initialOptions = initialQuestion.options && !Array.isArray(initialQuestion.options) ? Object.values(initialQuestion.options) : initialQuestion.options || ['', '', ''];
  const [form, setForm] = useState({ exam_name: initialQuestion.exam_name || '', category: initialQuestion.category || '', date: initialQuestion.date || '', shift: initialQuestion.shift || '', section: initialQuestion.section || '', question_number: initialQuestion.question_number || '', question: initialQuestion.question || '', correct_explanation: initialQuestion.correct_explanation || initialQuestion.answer_explanation || '', incorrect_explanation: initialQuestion.incorrect_explanation || '' });
  const [options, setOptions] = useState(initialOptions.length >= 2 ? initialOptions : ['', '']);
  const [keyStyle, setKeyStyle] = useState(Object.keys(initialQuestion.options || {}).some((key) => /^[A-Za-z]$/.test(key)) ? 'alpha' : 'numeric');
  const [correctAnswer, setCorrectAnswer] = useState(initialQuestion.correct_answer || '');
  const [error, setError] = useState('');
  const [matchTarget, setMatchTarget] = useState(null);
  const refs = { question: useRef(null), correct_explanation: useRef(null), incorrect_explanation: useRef(null) };
  const keys = keysFor(keyStyle, options.length);

  function updateField(event) { setForm((current) => ({ ...current, [event.target.name]: event.target.value })); }
  function insertText(field, value) { const element = refs[field].current; const start = element.selectionStart ?? element.value.length; const end = element.selectionEnd ?? start; setForm((current) => ({ ...current, [field]: `${current[field].slice(0, start)}${value}${current[field].slice(end)}` })); requestAnimationFrame(() => { element.focus(); element.selectionStart = element.selectionEnd = start + value.length; }); }
  function toolbar(field, type) { if (type === 'code') insertText(field, '\n```\n// your code here\n```\n'); else if (type === 'image') insertText(field, '\n![image](https://example.com/image.png)\n'); else setMatchTarget(field); }
  function changeKeyStyle(event) { setKeyStyle(event.target.value); setCorrectAnswer(''); }
  function submit(event) { event.preventDefault(); setError(''); const cleanOptions = Object.fromEntries(options.map((value, index) => [keys[index], value.trim()]).filter(([, value]) => value)); if (!form.category.trim() || !form.question.trim()) return setError('Category and question text are required.'); if (Object.keys(cleanOptions).length < 2) return setError('Please provide at least 2 non-empty options.'); if (!correctAnswer || !cleanOptions[correctAnswer]) return setError('Please select a valid correct answer.'); onSubmit({ ...form, category: form.category.trim(), question: form.question.trim(), question_number: form.question_number === '' ? undefined : Number(form.question_number), options: cleanOptions, correct_answer: correctAnswer, answer_explanation: form.correct_explanation.trim(), correct_explanation: form.correct_explanation.trim(), incorrect_explanation: form.incorrect_explanation.trim() }); }
  function addOption() { setOptions((current) => [...current, '']); }
  function removeOption(index) { if (options.length <= 2) return; setOptions((current) => current.filter((_, optionIndex) => optionIndex !== index)); if (correctAnswer === keys[index]) setCorrectAnswer(''); }
  const previewOptions = Object.fromEntries(options.map((value, index) => [keys[index], value]));

  return <form className="question-editor-form" onSubmit={submit}><div className="editor-metadata-grid"><EditorField label="Exam Name"><input name="exam_name" value={form.exam_name} onChange={updateField} placeholder="e.g. DSSSB TGT Computer Science" /></EditorField><EditorField label="Category *"><input name="category" list="question-categories" value={form.category} onChange={updateField} placeholder="e.g. DBMS, Java" /><datalist id="question-categories">{categories.map((category) => <option value={category} key={category} />)}</datalist></EditorField><EditorField label="Date"><input name="date" value={form.date} onChange={updateField} placeholder="e.g. 25 June 2023" /></EditorField><EditorField label="Shift"><input name="shift" value={form.shift} onChange={updateField} placeholder="e.g. Shift 2" /></EditorField><EditorField label="Section"><input name="section" value={form.section} onChange={updateField} placeholder="Optional" /></EditorField><EditorField label="Question Number"><input name="question_number" type="number" value={form.question_number} onChange={updateField} placeholder="Optional" /></EditorField></div>
    <EditorTextField label="Question *" field="question" value={form.question} onChange={updateField} reference={refs.question} onTool={toolbar} />
    <div className="editor-options-heading"><h4>Options *</h4><label>Key style <select value={keyStyle} onChange={changeKeyStyle}><option value="numeric">1, 2, 3...</option><option value="alpha">A, B, C...</option></select></label></div>
    <div className="editor-options-list">{options.map((value, index) => <div className="editor-option-row" key={`${index}-${keys[index]}`}><strong>{keys[index]}</strong><input value={value} onChange={(event) => setOptions((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} placeholder="Option text..." /><button type="button" onClick={() => removeOption(index)} aria-label={`Remove option ${keys[index]}`}>×</button></div>)}</div><button className="btn btn-secondary" type="button" onClick={addOption}>+ Add Option</button>
    <EditorField label="Correct Answer *"><select value={correctAnswer} onChange={(event) => setCorrectAnswer(event.target.value)}><option value="">Select correct answer</option>{keys.map((key, index) => <option value={key} key={key}>{key}: {options[index] || '(empty)'}</option>)}</select></EditorField>
    <EditorTextField label="Why the correct answer is correct" field="correct_explanation" value={form.correct_explanation} onChange={updateField} reference={refs.correct_explanation} onTool={toolbar} />
    <EditorTextField label="Why the other options are incorrect" field="incorrect_explanation" value={form.incorrect_explanation} onChange={updateField} reference={refs.incorrect_explanation} onTool={toolbar} />
    {error && <p className="form-error" role="alert">{error}</p>}<div className="editor-actions"><button className="btn btn-primary" type="submit">{submitLabel}</button>{onCancel && <button className="btn btn-secondary" type="button" onClick={onCancel}>Cancel</button>}{onDelete && <button className="btn btn-secondary editor-delete" type="button" onClick={onDelete}>Delete This Question</button>}</div>{statusMessage && <p className="success-message editor-status" role="status">{statusMessage}</p>}{statusError && <p className="form-error editor-status" role="alert">{statusError}</p>}
    <div className="editor-preview glass-card"><h4>Live Preview</h4><div className="question-text"><ContentRenderer text={form.question || 'Start typing to see a preview...'} /></div><div className="options-list">{Object.entries(previewOptions).filter(([, value]) => value).map(([key, value]) => <div className="question-option-card" key={key}><span className="option-indicator">{key}</span><ContentRenderer text={value} /></div>)}</div><div className="explanation-panel preview-explanation"><div className="explanation-title">📝 Explanation</div><ContentRenderer text={form.correct_explanation} /></div></div>
    {matchTarget && <MatchColumnsModal onInsert={(value) => { insertText(matchTarget, value); setMatchTarget(null); }} onClose={() => setMatchTarget(null)} />}
  </form>;
}

function EditorField({ label, children }) { return <label className="editor-field"><span>{label}</span>{children}</label>; }
function EditorTextField({ label, field, value, onChange, reference, onTool }) { return <div className="editor-text-field"><span>{label}</span><div className="editor-toolbar"><button type="button" onClick={() => onTool(field, 'code')}>Insert Code</button><button type="button" onClick={() => onTool(field, 'image')}>Insert Image</button><button type="button" onClick={() => onTool(field, 'match')}>Insert Match Columns</button></div><textarea name={field} value={value} onChange={onChange} ref={reference} placeholder="Type here..." /></div>; }
function MatchColumnsInline({ onInsert, onCancel }) { const [rows, setRows] = useState([['', ''], ['', '']]); const [headers, setHeaders] = useState(['Column-I', 'Column-II']); const roman = ['i', 'ii', 'iii', 'iv', 'v', 'vi']; return <div className="inline-match-builder"><h4>Insert Match the Columns</h4><div className="editor-metadata-grid"><input value={headers[0]} onChange={(event) => setHeaders([event.target.value, headers[1]])} /><input value={headers[1]} onChange={(event) => setHeaders([headers[0], event.target.value])} /></div>{rows.map((row, index) => <div className="match-builder-row" key={index}><input value={row[0]} onChange={(event) => setRows((current) => current.map((item, itemIndex) => itemIndex === index ? [event.target.value, item[1]] : item))} placeholder={`a${index + 1}) Column I item`} /><input value={row[1]} onChange={(event) => setRows((current) => current.map((item, itemIndex) => itemIndex === index ? [item[0], event.target.value] : item))} placeholder={`${roman[index]}) Column II item`} /></div>)}<button className="btn btn-secondary" type="button" onClick={() => setRows((current) => [...current, ['', '']])}>+ Add Row</button><div className="editor-actions"><button className="btn btn-primary" type="button" onClick={() => onInsert(`\n${headers[0]}: ${rows.map((row, index) => `${String.fromCharCode(97 + index)}) ${row[0]}`).join(' ')} ${headers[1]}: ${rows.map((row, index) => `${roman[index] || `r${index + 1}`}) ${row[1]}`).join(' ')}\n`)}>Insert</button><button className="btn btn-secondary" type="button" onClick={onCancel}>Cancel</button></div></div>; }
export default QuestionEditorForm;
